service: java8-micronaut-performance

provider:
  name: aws
  region: eu-west-1
  tracing:
    lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource:
        - !GetAtt ProductsTable.Arn

custom:
  defaultArtifact: build/distributions/lambda-micronaut-0.1.zip

package:
  artifact: ${opt:artifact, self:custom.defaultArtifact}

functions:
  ping:
    name: ${self:service}-ping-${self:provider.stage}
    handler: be.drissamri.StreamLambdaHandler::handleRequest
    runtime: java8
    memorySize: 1024
    events:
      - http:
          path: /products
          method: post

resources:
  Resources:
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: products
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
